#!/bin/bash

if [ "$#" -ne 1 ] || ! [[ $1 =~ ^[0-9]{4}$ ]]; then
  echo "Usage : $0 <4-digit-integer>"
  exit 1
fi
echo -n "$1" | sha256sum > hash_output.txt
echo "Hash generated successfully and saved to hash_output.txt"
